### PR TITLE
Issue #361: Add option to disable TLS peer verification for testing purposes

### LINKED ISSUE #361: API Url - HTTP vs. HTTPS vs. Unsigned Certificates
If you use a self signed certificate, e.g. while development, the api request during an export will always fail because of a empty response body in http request.

I could fix it by either using a HTTP url instead HTTPS or by adding `"verify_peer" => false, "verify_peer_name" => false` to the request context in the `doPutRequests` and `doGetRequest` methods of `lib/LizardsAndPumpkins/src/Api/PhpStreamHttpApiClient.php`.

This might not be a typical setting for production but could be a bit confusing while development.

### PR DESCRIPTION
**Pull request by Vinai**
Closes #361

### CODE REVIEW

File: lib/LizardsAndPumpkins/src/Api/InsecurePhpStreamHttpApiClient.php [hunk 1]
```diff
@@ -0,0 +1,16 @@
+<?php
+
+declare(strict_types=1);
+
+namespace LizardsAndPumpkins\MagentoConnector\Api;
+
+class InsecurePhpStreamHttpApiClient extends PhpStreamHttpApiClient
+{
+    protected function buildStreamContextOptions(array $streamContextOptions)
```
Comment (tim-bezhashvyly) [inline lib/LizardsAndPumpkins/src/Api/InsecurePhpStreamHttpApiClient.php]: Maybe final?

Comment (tim-bezhashvyly) [inline lib/LizardsAndPumpkins/src/Api/InsecurePhpStreamHttpApiClient.php]: PHPDoc block is missing.

File: lib/LizardsAndPumpkins/src/Api/PhpStreamHttpApiClient.php [hunk 2]
```diff
@@ -12,11 +12,11 @@ class PhpStreamHttpApiClient implements HttpApiClient
      */
     public function doPutRequest($url, $body, array $headers)
     {
-        $httpRequestContext = stream_context_create(['http' => [
-            'method' => 'PUT',
-            'header' => $this->concatHeaderNamesAndValues($headers),
+        $httpRequestContext = stream_context_create(['http' => $this->buildStreamContextOptions([
+            'method'  => 'PUT',
+            'header'  => $this->concatHeaderNamesAndValues($headers),
```
Comment (tim-bezhashvyly) [inline lib/LizardsAndPumpkins/src/Api/PhpStreamHttpApiClient.php]: You have to reconfigure your IDE to avoid this.

File: magento-plugin/app/code/community/LizardsAndPumpkins/MagentoConnector/Helper/Factory.php [hunk 3]
```diff
@@ -254,4 +255,11 @@ public function createStockBuilder()
     {
         return new StockBuilder();
     }
+
+    public function createHttpApiClient()
```
Comment (tim-bezhashvyly) [inline magento-plugin/app/code/community/LizardsAndPumpkins/MagentoConnector/Helper/Factory.php]: PHPDoc block is missing.

File: lib/LizardsAndPumpkins/src/Api/PhpStreamHttpApiClient.php (hunk 2 above)
Comment (Vinai) [inline lib/LizardsAndPumpkins/src/Api/PhpStreamHttpApiClient.php]: Why avoid it?

Comment (Vinai) [inline lib/LizardsAndPumpkins/src/Api/PhpStreamHttpApiClient.php]: Why avoid it?

Comment (tim-bezhashvyly) [inline lib/LizardsAndPumpkins/src/Api/PhpStreamHttpApiClient.php]: Well, I don't care if it is indented or not. We must agree on formatting.
